---
title: "README"
author: "Cesar Prieto, Alejandro Urrego"
date: "`r Sys.Date()`"
output: html_document
editor_options:
   markdown:
     wrap: sentence
---

# Repository of Statistical Analysis of Social Networks

Welcome to the Social Networks repository.
This space is dedicated to the study, analysis and application of techniques related to the analysis of Social Networks.
From basic models to advanced approaches, this repository provides resources, tools, and examples for understanding and working with relational data.

## What will you find here?

### Documentation:

- Guides and tutorials on key concepts in Social Network analysis.

- References to bibliography and useful resources to delve deeper into the topic.

### Group Projects:

- Space to collaborate on group projects related to Social Networks.

- ideas, code and results with your classmates.

### Individual Projects:

- Opportunities to develop and share individual projects.

- Explore specific areas of interest or apply particular techniques to unique data sets.

### Example Code:

- Implementations of algorithms and common methods in the analysis of Social Networks.

- Clean, well-documented code examples to help you get started quickly.

### Additional Resources:

- Links to libraries, tools and data sets relevant to Social Network analysis.

- Complementary material to strengthen your skills and knowledge.

## Collaboration

We encourage you to contribute and collaborate in this repository!
If you have ideas, improvements, or projects you want to share, feel free to submit a Pull Request or open an Issue.
This space is for the academic community to grow and learn together.
